export const productColors = [
    { name: "Rouge", value: "#FF0000" },
    { name: "Bleu", value: "#0000FF" },
    { name: "Vert", value: "#008000" },
    { name: "Noir", value: "#000000" },
    { name: "Blanc", value: "#FFFFFF" },
    { name: "Jaune", value: "#FFD600" },
    { name: "Orange", value: "#FF9800" },
    { name: "Violet", value: "#9C27B0" },
    { name: "Rose", value: "#E91E63" },
    { name: "Marron", value: "#795548" },
    { name: "Gris", value: "#9E9E9E" },
    { name: "Beige", value: "#F5F5DC" },
    { name: "Marine", value: "#001F54" },
    { name: "Turquoise", value: "#1DE9B6" },
    { name: "Olive", value: "#808000" },
    { name: "Cyan", value: "#00BCD4" },
    { name: "Citron vert", value: "#CDDC39" },
    { name: "Sarcelle", value: "#009688" },
    { name: "Indigo", value: "#3F51B5" },
    { name: "Corail", value: "#FF7F50" },
    { name: "Or", value: "#FFD700" },
    { name: "Argent", value: "#C0C0C0" },
    { name: "Bordeaux", value: "#800000" },
    { name: "Menthe", value: "#AAF0D1" },
];